server:
  port: ${PORT:8080}
  forward-headers-strategy: framework

spring:
  data:
    mongodb:
      uri: mongodb+srv://enowbrenda91106:clexis91106@cluster0.fnr4gwb.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: clexis-db  # <-- Add this line

defaultUser:
  username: admin
  email: admin.clexis@gmail.com
  password: admin
  role: ADMIN

api:
  ai:
    host:
    port: 3001
    generateResource: ${api.ai.host}:${api.ai.port.port}/api/v1/clexis_ai/tools/generate
    getStudentMatches: ${api.ai.host}:${api.ai.port.port}/api/v1/clexis_ai/tools/generate
    resourceRecommendation: ${api.ai.host}:${api.ai.port.port}/api/v1/clexis_ai/resources/propose
  notification:
    host:
    port: 3002
    sendEmail: ${api.ai.host}:${api.ai.port.port}/api/v1/clexis_notification/sendEmail
