package com.brenda.clexis.clientGatewayService.model.enums;

public enum ConfigKey {
    CLIENT_EXIST , GET_SCORING , REQUEST_LOAN,INITIATE_LOAN,GET_LOAN ,GET_ALL_LOANS,GET_PLATFORM_LOAN,PREPARE_SCORING,GET_CLIENT_TRANSACTIONS,CHANGE_LANGUAGE
}
